removed course offering page on the homepage and added them to the course offering page
ucsb-cs56-f19/ucsb-tutor-scheduler pull request #45
Opened 2019-12-03 05:04 UTC by voidii

Also added nav bar and tutor assignments to the course offering page

2019-12-03 20:08 UTC, pconrad submitted a review, later dismissed
There are some places where merge conflicts were not resolved, and as a result, this code no longer compiles, and thus it fails on CI.

I suggest updating this branch on localhost, and doing a `mvn clean compile` and then a `mvn test` to get it into a state where it at least compiles before we look at it further.

2019-12-03 20:13 UTC, pconrad commented
@voidii please see the comments above

2019-12-03 22:16 UTC, voidii commented
OK, I used vs code to open the files and it seems like there are some changes that were not accepted. Now I have accepted those changes and they compile nicely now. I will a second check on the localhost to make sure everything is alright and push the changes to our branch.

2019-12-03 23:42 UTC, voidii commented
The code compiles fine now and is up to date with master branch and I have also removed the course offering table from the main page but it seems to not be able to direct to the course offering page that we created. It was working on the previous version but not anymore. I will look further into that and will later push a working version.

2019-12-04 05:06 UTC, yinonrousso requested changes
Courses offering table and tutor assignment table were removed from the homepage but gave no alternative route to access their individual pages. I may hold off on pulling this until a navigation button brings me to a specific tutor assignment page and course offering page.

2019-12-05 00:39 UTC, voidii commented
Fix the page and nav bar, should work fine now

2019-12-05 01:53 UTC, yinonrousso requested changes
Need to resolve merge conflicts

2019-12-05 02:08 UTC, jingjingyu123 commented
conflict should be resloved

2019-12-05 02:31 UTC, yinonrousso commented on src/main/resources/templates/fragments/basic_form.html
> +
Please remove commented out code

2019-12-05 02:31 UTC, yinonrousso commented on src/main/resources/templates/fragments/basic_form.html
> +    <!--
Same here rm commented out code

2019-12-05 02:34 UTC, yinonrousso approved these changes
I removed left over commented out code. The rest looks good. May want to add better navigation to new course offerings page

2019-12-05 02:34 UTC, yinonrousso commented on src/main/resources/templates/fragments/basic_form.html
> +
I removed the comments myself

2019-12-05 02:39 UTC, merged